### ISSUE TITLE
FFMPEG 4 is out

### ISSUE THREAD

**Issue by sdvillal** [loopbio/ffmpeg-feedstock#8]
Some interesting stuff in there:
https://git.ffmpeg.org/gitweb/ffmpeg.git/shortlog/n4.0

```
April 20th, 2018, FFmpeg 4.0 "Wu"
FFmpeg 4.0 "Wu", a new major release, is now available! Some of the highlights:

Bitstream filters for editing metadata in H.264, HEVC and MPEG-2 streams
Experimental MagicYUV encoder
TiVo ty/ty+ demuxer
Intel QSV-accelerated MJPEG encoding
native aptX and aptX HD encoder and decoder
NVIDIA NVDEC-accelerated H.264, HEVC, MJPEG, MPEG-1/2/4, VC1, VP8/9 hwaccel decoding
Intel QSV-accelerated overlay filter
mcompand audio filter
acontrast audio filter
OpenCL overlay filter
video mix filter
video normalize filter
audio lv2 wrapper filter
VAAPI MJPEG and VP8 decoding
AMD AMF H.264 and HEVC encoders
video fillborders filter
video setrange filter
support LibreSSL (via libtls)
Dropped support for building for Windows XP. The minimum supported Windows version is Windows Vista.
deconvolve video filter
entropy video filter
hilbert audio filter source
aiir audio filter
Removed the ffserver program
Removed the ffmenc and ffmdec muxer and demuxer
VideoToolbox HEVC encoder and hwaccel
VAAPI-accelerated ProcAmp (color balance), denoise and sharpness filters
Add android_camera indev
codec2 en/decoding via libcodec2
native SBC encoder and decoder
drmeter audio filter
hapqa_extract bitstream filter
filter_units bitstream filter
AV1 Support through libaom
E-AC-3 dependent frames support
bitstream filter for extracting E-AC-3 core
Haivision SRT protocol via libsrt
vfrdet filter
We strongly recommend users, distributors, and system integrators to upgrade unless they use current git master.
```

**Comment by nzjrs** [comment]
Weird. They already have nvidia hwaccel. I wonder what is really New?

**Comment by sdvillal** [comment]
Seems that CF might be getting soon version 4.
https://github.com/conda-forge/ffmpeg-feedstock/pull/47

**Comment by nzjrs** [comment]
Remember, there is an unmerged python-loopb branch for our opencv-ffmpeg builds, and we are not even using 3.4.x in loopy / ci / tests / anything. Lets walk before we run at least....

**Comment by nzjrs** [comment]
> NVIDIA NVDEC-accelerated H.264, HEVC, MJPEG, MPEG-1/2/4, VC1, VP8/9 hwaccel decoding

I'll repeat again - this makes no sense. maybe they are just advertising that you can build it without the nvidia SDK?

**Comment by sdvillal** [comment]
A new recipe adapted to aligh better with latest CF developemnts (use the newer CB3 syntax, so future proof when I'm not there) + having proper pinnings + explicily telling which nvidia drivers are supported (but tough experience seems to indicate we should build a noncuda variant and use it by default) + other small goodies (getting a bit more featureful with codecs: libvpx, aom, x265) is there to use whenever we test it enough.
