### ISSUE TITLE
Build NVENC (+ NVDEC?) variant

### ISSUE THREAD

**Issue by sdvillal** [loopbio/ffmpeg-feedstock#9]
Low priority issue, as we only use this in recording settings where we are all fine. We need to compile against software versions that support oldie (pre 390) drivers.

We can either:
  1- build a static version and create another package ffmpeg-static-nvenc
  2- build a variant of our packages (will try this first)

For 2), just branch out both GPL and LGPL, set the docker image to use to anvil-nvidia and add the needed deps + configure settings; add these to the build string (we might want to also add classifier to the non-cuda variant, as usual, we will need to do some funambulism until conda decides to implement better package provides/conflicts tools).

Links:
seems simple: https://developer.nvidia.com/ffmpeg
video codec sdk: https://developer.nvidia.com/nvidia-video-codec-sdk
arch superpack: https://aur.archlinux.org/packages/ffmpeg-full/
first google results: 
 - https://gist.github.com/Brainiarc7/988473b79fd5c8f0db54b92ebb47387a
 - https://github.com/lutris/ffmpeg-nvenc
 - https://gist.github.com/Brainiarc7/3f7695ac2a0905b05c5b

**Comment by maxlklaxl** [comment]
Video SDK 7
* loopbio/software/hw_enc_dec/Video_Codec_SDK_7.0.1.zip

**Comment by nzjrs** [comment]
remember, the goal of this is that without x264 it is no longer GPL, so starting with the lgpl version of our package seems unnecessary.

Also, there must be something else going on because we have certainly used the NVENC build with more recent versions of the nvidia driver than it was built with. So there is some binay compatibility retained. How this intersects with the SDK version, I am not sure.

**Comment by sdvillal** [comment]
I'm unsure we need the SDK at all anymore, it seems to me everything needed is provided in the ffmpeg source tree (so we just need cuda).

I will try first to build on both variants (LGPL and GPL) under the premise that is just 10% more work and at some point we might want to have libx264 and nvenc on the same build (benchmark?).

**Comment by maxlklaxl** [comment]
we need SDK 7 to support the older driver version, to be specific 367 and successors, newer driver versions are compatible

**Comment by maxlklaxl** [comment]
at some point (>ffmpeg 3.1.2??) they included the nvenc headers but moved them to a separate repo later

https://git.videolan.org/?p=ffmpeg.git;a=commit;h=27cbbbb33f259de7c795d2b75edf7b240f0f82e6

**Comment by nzjrs** [comment]
> External headers are no longer welcome in the ffmpeg codebase because they
> increase the maintenance burden

owww, feel the burn

**Comment by sdvillal** [comment]
One quick question. Is QSV useful? I saw you also have some builds with the intel media sdk. I could aim for a ffmpeg build stacking all the accelerations you like. So I think I will call this build "full", get the nvidia stuff working and tackle anything you want at different time.

**Comment by nzjrs** [comment]
I suggest ignoring QSV. Max wasted weeks on it. It depends too much on kernel version and intel driver state. Its a bit of a joke.

**Comment by maxlklaxl** [comment]
ignore QSV! as John says, it's a joke. 

VAAPI could be interesting, I think it is enabled by default? ... but super low priority!

**Comment by sdvillal** [comment]
FYI in my systems I use a ffmpeg build has all these options enabled. So if you want to test something without the hassle to compile yourself, and you do have already the benchmarks to run, just let me know and I do for you.

A question here is where will we put the generated packages. In general we will now be activating non-free parts of ffmpeg. I would not really worry and still put in our public conda channel. But if we worry, it could be a good time to explore private repos for conda packages. anaconda has put the prices down but it would still 47$/month (bar negotiations) to bump our org account in anaconda.org, else we could just explore AWS.

**Comment by sdvillal** [comment]
Or I'm missing something, or we actually do not need any special compilation config to get nvenc on. Our package does include already these encoders and they work as long as the system has a suitable gpu (checked in my laptop and loopg). The encoders are missing from the static package though.

So I will close this as a lucky lazy do nothing, and see how I adapt RecorderFFMPEG to use ffmpeg. Please reopen if you think I'm a big moron.
